package com.leetcode.easy;// Given two strings s and t which consist of only lowercase letters.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Find the letter that was added in t.
// Input:
// s = "abcd"
// t = "abcde"
// Output:
// e
// Explanation:
// 'e' is the letter that was added.

public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        // HashMap<Character,Integer> smap = new HashMap<Character,Integer>();
        // for(int i = 0; i < s.length(); i++){
        //     Character x = s.charAt(i);
        //     if(smap.containsKey(x)){
        //         smap.put(x,smap.get(x)+1);
        //     } else {
        //         smap.put(x,1);
        //     }
        // }
        // for(int i = 0; i< t.length(); i++){
        //     Character x = t.charAt(i);
        //     int c = smap.get(x) == null ? 0 : smap.get(x);
        //     if(c > 0){
        //         smap.put(x,--c);
        //     } else{
        //         return x;
        //     }
        // }
        // return 'x';
        
        int[] ar = new int[26];
        for(int i = 0; i < s.length(); i++){
            ar[s.charAt(i) - 'a']++;
        }
        char res = 'a';
        for(int i = 0; i < t.length(); i++){
            int x = t.charAt(i) - 'a';
            ar[x]--;
            if(ar[x] < 0){
                res = t.charAt(i);
            }
        }
        return res;
        
    //     char x = t.charAt(t.length()-1);
    //     for (int i = 0; i < t.length()-1 ; i++) {
    //         x ^= s.charAt(i) ^ t.charAt(i);

	   //  }
	   //     return x;
    }
}
